---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-pc-deploy
spec:
  replicas: 2  
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: wissenbaba/petclinic:2
        ports:
        - containerPort: 80  # Port exposed by your Docker image
...
